Use global.imagePullSecrets at solr-operator helm chart #338
apache/solr-operator pull request #343
Opened 2021-10-13 17:02 UTC by j-coll

Same PR as #339, but against main branch

2021-10-14 22:06 UTC, HoustonPutman requested changes
Thanks for the contribution, this would indeed be very helpful for people!

Before merging would you mind adding a Changelog entry here:
https://github.com/apache/solr-operator/blob/main/helm/solr-operator/Chart.yaml#L56

And adding an entry to the helm chart documentation as well?
https://github.com/apache/solr-operator/blob/main/helm/solr-operator/README.md#running-the-solr-operator

2021-11-09 17:21 UTC, HoustonPutman commented
Well if you want to share imagePullSecrets here, you can merely use the same serviceAccount that is created by the Zookeeper Operator with the Solr Operator. That way the imagePullSecrets will be available to both through the same serviceAccount.

```yaml
serviceAccount:
  create: false
  name: operator-account

zookeeper-operator:
  install: true
  serviceAccount:
     create: true
     name: operator-account
     imagePullSecrets:
        - list
        - of
        - strings
```

Using the above helm values, the zookeeper-operator helm chart will create the serviceAccount with the listed imagePullSecrets. Then the Solr Operator will merely use the same one, named `operator-account`.

No need to actually use the global imagePullSecrets.

2023-03-19 19:48 UTC, piotrrybicki commented
Hello there. @j-coll are you willing to do proper changes in this PR?
I'd love to have ability to provide imagePullSecrets in globals. I'm not using ZK operator.

I can also create my own PR about this issue.

2023-03-28 14:35 UTC, HoustonPutman commented
@piotrrybicki Please open your own PR. We'd love to support as many globals as possible, to make setup easy for everyone!

As for my comment above it would be great if the helm code could detect a list of strings and convert it to a list of objects where necessary.

2026-03-05 18:43 UTC, janhoy commented
@j-coll Are you still planning to land this?

2026-06-18 18:36 UTC, HoustonPutman commented
Closing in favor of #832 . Thanks for the work here, sorry we weren't able to get it through before.

2026-06-18 18:36 UTC, closed without merging