Make security context configurable.
apache/solr-operator pull request #566
Opened 2023-05-15 09:38 UTC by uluzox

2023-05-15 14:30 UTC, HoustonPutman requested changes
This looks great, just one suggestion for the documentation. Thanks for contributing!

Would you mind also adding a changelog entry to the Chart.yaml? You will have to remove the two entries that are there as placeholders now, but you can see an example of this here: https://github.com/apache/solr-operator/commit/0539494189c6634b6ecb91ac5e09809df4c5b630#diff-5e33a9126c77070c5c0eb99dda42378496c379464576c543c5f9a731da91284f

2023-05-15 14:30 UTC, HoustonPutman commented on helm/solr-operator/README.md
> +| securityContext | map[string]string | `allowPrivilegeEscalation: false, runAsNonRoot: true` | Provide security context for the Solr Operator container |
```suggestion
| securityContext | object | `allowPrivilegeEscalation: false, runAsNonRoot: true` | Provide security context for the Solr Operator container |
```

the securityContext is an object, that can have values that aren't strings. So we shouldn't use `map[string]string` as the type.

2023-05-15 18:13 UTC, uluzox commented
> This looks great, just one suggestion for the documentation. Thanks for contributing!
> 
> Would you mind also adding a changelog entry to the Chart.yaml? You will have to remove the two entries that are there as placeholders now, but you can see an example of this here: [0539494#diff-5e33a9126c77070c5c0eb99dda42378496c379464576c543c5f9a731da91284f](https://github.com/apache/solr-operator/commit/0539494189c6634b6ecb91ac5e09809df4c5b630#diff-5e33a9126c77070c5c0eb99dda42378496c379464576c543c5f9a731da91284f)

Thanks for the review, @HoustonPutman. Could you please have another look?

2023-05-16 20:39 UTC, merged

2023-05-16 20:40 UTC, HoustonPutman commented
Thanks @uluzox!